spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: pass
  jpa:
    # TODO - false in production
    show-sql: true
    hibernate:
      ddl-auto: update
feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000
        writeTimeout: 60000
