spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: pass
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update